import type { Product } from "@/types";
import { SEO_KEYWORDS } from "@/lib/seo-keywords";

export const products: Product[] = [
  {
    slug: "sodium-metasilicate-granules",
    name: "Sodium Metasilicate Granules",
    shortName: "Granules",
    cas: "6834-92-0",
    formula: "Na₂SiO₃",
    categoryParent: "sodium-metasilicate",
    primaryKeyword: SEO_KEYWORDS.granules.primary,
    metaTitle: SEO_KEYWORDS.granules.title,
    metaDescription: SEO_KEYWORDS.granules.description,
    keywords: ["sodium metasilicate granules specifications", "granule mesh size"],
    summary:
      "Granular sodium metasilicate product information for buyers reviewing particle size, handling, detergent compatibility, packing, documents, and RFQ details.",
    description: [
      "Sodium metasilicate granules are a free-flowing Na₂SiO₃ form used where easier handling, controlled dosing, lower dust, and stable storage are important in industrial formulations.",
      "This form is commonly reviewed by detergent plants, cleaning compound producers, ceramic processors, metal treatment users, and distributors that need clear particle-size and packing confirmation before quotation.",
      "Before ordering granular sodium metasilicate, buyers should confirm target mesh size, Na₂O, SiO₂, Fe, water insoluble matter, appearance, packing method, loading quantity, destination port, and required documents.",
    ],
    specs: [
      { label: "Product Name", value: "Sodium Metasilicate Granules" },
      { label: "Chinese Name", value: "颗粒偏硅酸钠" },
      { label: "CAS No.", value: "6834-92-0" },
      { label: "Chemical Formula", value: "Na₂SiO₃" },
      { label: "Molecular Weight", value: "122.06 g/mol" },
      { label: "Appearance", value: "White to off-white granules" },
      { label: "SiO₂ Content", value: "≥ 46.0%" },
      { label: "Na₂O Content", value: "≥ 50.0%" },
      { label: "Fe Content", value: "≤ 0.02%" },
      { label: "Water Insoluble", value: "≤ 0.2%" },
      { label: "Particle Size", value: "8–40 mesh (customizable)" },
      { label: "Bulk Density", value: "Available on request" },
      { label: "Whiteness", value: "Available on request for detergent applications" },
      { label: "pH", value: "Strongly alkaline; confirm by TDS" },
      { label: "Documents Available", value: "MSDS, COA, TDS, certificates on request" },
    ],
    applications: [
      "Laundry powder and dishwashing detergent builder systems",
      "Industrial cleaning compound formulations requiring easier dosing",
      "Ceramic and refractory processing where alkaline silicate support is needed",
      "Metal surface cleaning and degreasing preparations",
      "Distributor repacking or stock supply where granular handling is preferred",
    ],
    packaging: [
      "25 kg PP woven bags with PE liner for standard export handling",
      "50 kg woven bags with PE liner by order requirement",
      "1,000 kg jumbo bags (FIBC) for bulk handling review",
      "Neutral bag, printed bag, palletized or non-palletized loading can be confirmed before quotation",
      "Custom label, batch number and handling marks can be reviewed with the purchase order",
    ],
    features: [
      "Granular form supports cleaner handling, easier dosing and reduced dust compared with fine powder",
      "Particle size such as 8–40 mesh can be reviewed against buyer application needs",
      "Detergent buyers can request appearance, whiteness and Fe review before order confirmation",
      "RFQ should include target mesh size, quantity, packing, destination port and required documents",
      "MSDS / SDS, TDS and batch-specific COA can be requested according to order requirements",
    ],
  },
  {
    slug: "sodium-metasilicate-anhydrous",
    name: "Sodium Metasilicate Anhydrous",
    shortName: "Anhydrous",
    cas: "6834-92-0",
    formula: "Na₂SiO₃",
    categoryParent: "sodium-metasilicate",
    primaryKeyword: SEO_KEYWORDS.anhydrous.primary,
    metaTitle: SEO_KEYWORDS.anhydrous.title,
    metaDescription: SEO_KEYWORDS.anhydrous.description,
    keywords: ["anhydrous Na2SiO3 specifications", "low moisture metasilicate"],
    summary:
      "Anhydrous sodium metasilicate technical information for buyers reviewing low-moisture Na₂SiO₃, dry blend compatibility, packing, documents, and RFQ requirements.",
    description: [
      "Anhydrous sodium metasilicate is the low-moisture Na₂SiO₃ grade selected for dry blend systems where water introduction should be minimized.",
      "It is commonly reviewed for high-alkalinity detergent formulations, industrial cleaning compounds, metal degreasing systems, and selected processing applications that require stable dry material handling.",
      "Before quotation, buyers should confirm Na₂O, SiO₂, Fe, moisture, appearance, particle size or bulk density requirements, packing method, storage conditions, MSDS / SDS, TDS and batch COA needs.",
    ],
    specs: [
      { label: "Product Name", value: "Anhydrous Sodium Metasilicate" },
      { label: "Chinese Name", value: "无水偏硅酸钠" },
      { label: "CAS No.", value: "6834-92-0" },
      { label: "Chemical Formula", value: "Na₂SiO₃" },
      { label: "Molecular Weight", value: "122.06 g/mol" },
      { label: "Appearance", value: "White powder or fine granules" },
      { label: "SiO₂ Content", value: "≥ 46.0%" },
      { label: "Na₂O Content", value: "≥ 50.0%" },
      { label: "Fe Content", value: "≤ 0.02%" },
      { label: "Moisture", value: "≤ 1.0%" },
      { label: "Bulk Density", value: "Available on request" },
      { label: "Particle Size", value: "Subject to buyer specification" },
      { label: "pH", value: "Strongly alkaline; confirm by TDS" },
      { label: "Storage", value: "Keep sealed and dry; avoid moisture absorption" },
      { label: "Documents Available", value: "MSDS, COA, TDS, certificates on request" },
    ],
    applications: [
      "High-alkalinity detergent and cleaning powder formulations",
      "Industrial degreasing compounds for metal cleaning operations",
      "Dry blend chemical systems where low moisture is required",
      "Paper and pulp processing chemical formulations",
      "Selected oilfield or drilling fluid additive applications subject to buyer specification",
    ],
    packaging: [
      "25 kg PP woven bags with PE liner for moisture protection",
      "50 kg woven bags with PE liner by order requirement",
      "1,000 kg jumbo bags (FIBC) for bulk order handling",
      "Keep sealed and dry during storage and transport; final packing confirmed before quotation",
      "Palletized or non-palletized loading can be reviewed according to destination and buyer handling method",
    ],
    features: [
      "Low-moisture grade for dry blend stability and reduced moisture introduction",
      "Suitable for high-alkalinity industrial cleaning and detergent systems",
      "Na₂O, SiO₂, Fe, moisture and appearance should be checked by selected grade specification",
      "RFQ should include target moisture requirement, particle size or bulk density if required",
      "MSDS / SDS, TDS and batch-specific COA can be requested with order details",
    ],
  },
  {
    slug: "sodium-metasilicate-pentahydrate",
    name: "Sodium Metasilicate Pentahydrate",
    shortName: "Pentahydrate",
    cas: "10213-79-3",
    formula: "Na₂SiO₃·5H₂O",
    categoryParent: "sodium-metasilicate",
    primaryKeyword: SEO_KEYWORDS.pentahydrate.primary,
    metaTitle: SEO_KEYWORDS.pentahydrate.title,
    metaDescription: SEO_KEYWORDS.pentahydrate.description,
    keywords: ["pentahydrate Na2SiO3 specifications", "crystalline metasilicate"],
    summary:
      "Sodium metasilicate pentahydrate technical information for buyers reviewing Na₂SiO₃·5H₂O hydrate grade, crystal form, packing, documents, and RFQ details.",
    description: [
      "Sodium metasilicate pentahydrate is a hydrated crystalline Na₂SiO₃·5H₂O grade used where a crystal or hydrated metasilicate form is preferred for formulation and handling.",
      "Common purchasing scenarios include cleaning products, textile auxiliaries, water treatment blends, metal cleaning preparations, and distributors that need hydrate-grade documentation before placing orders.",
      "Before quotation, buyers should confirm CAS 10213-79-3, Na₂O, SiO₂, Fe, water insoluble matter, appearance, particle size, packing, storage conditions, MSDS / SDS, TDS and COA requirements.",
    ],
    specs: [
      { label: "Product Name", value: "Sodium Metasilicate Pentahydrate" },
      { label: "Chinese Name", value: "五水偏硅酸钠" },
      { label: "CAS No.", value: "10213-79-3" },
      { label: "Chemical Formula", value: "Na₂SiO₃·5H₂O" },
      { label: "Molecular Weight", value: "212.14 g/mol" },
      { label: "Appearance", value: "White crystalline granules or powder" },
      { label: "SiO₂ Content", value: "≥ 28.5%" },
      { label: "Na₂O Content", value: "≥ 29.0%" },
      { label: "Fe Content", value: "≤ 0.02%" },
      { label: "Bulk Density", value: "Available on request" },
      { label: "Particle Size", value: "Subject to grade and buyer requirement" },
      { label: "Water Insoluble", value: "Confirmed by grade specification" },
      { label: "pH", value: "Strongly alkaline; confirm by TDS" },
      { label: "Storage", value: "Keep sealed and dry; avoid moisture absorption" },
      { label: "Documents Available", value: "MSDS, COA, TDS, certificates on request" },
    ],
    applications: [
      "Household and institutional cleaning product formulations",
      "Water treatment chemical blends requiring hydrated metasilicate review",
      "Textile scouring and bleaching auxiliary formulations",
      "Metal cleaning preparations where controlled dissolution is required",
      "Distributor supply for buyers specifying CAS 10213-79-3 pentahydrate grade",
    ],
    packaging: [
      "25 kg PP woven bags with PE liner for standard export orders",
      "50 kg woven bags with PE liner by order requirement",
      "1,000 kg jumbo bags (FIBC) for bulk procurement review",
      "Neutral bag, printed bag, palletized or non-palletized loading can be confirmed before quotation",
      "Store sealed and dry; avoid moisture exposure during storage and transport",
    ],
    features: [
      "Hydrated Na₂SiO₃·5H₂O grade for buyers specifying pentahydrate material",
      "Crystalline appearance and dissolution behavior should be confirmed by selected grade specification",
      "Suitable for selected cleaning, textile and water treatment formulation reviews",
      "RFQ should include required hydrate grade, particle size or appearance needs, packing and destination port",
      "MSDS / SDS, TDS and batch-specific COA can be requested according to order requirements",
    ],
  },
  {
    slug: "sodium-silicate",
    name: "Sodium Silicate",
    shortName: "Sodium Silicate",
    cas: "1344-09-8",
    formula: "Na₂O·nSiO₂",
    primaryKeyword: SEO_KEYWORDS.sodiumSilicate.primary,
    metaTitle: SEO_KEYWORDS.sodiumSilicate.title,
    metaDescription: SEO_KEYWORDS.sodiumSilicate.description,
    keywords: ["liquid sodium silicate", "sodium silicate exporter China"],
    summary:
      "Liquid sodium silicate product information for buyers reviewing water glass, modulus selection, solid content, liquid packing, documents, and RFQ preparation.",
    description: [
      "Sodium silicate, also known as water glass, is primarily reviewed here as a liquid silicate product line for industrial formulations, binder systems, construction materials, paper production and water treatment applications.",
      "The key purchasing decision is normally modulus and solid content, followed by appearance, density, packing method, storage conditions, destination, and required documents.",
      "If solid sodium silicate is required, buyers should state the requested form separately so the quotation can distinguish liquid supply from lump or granule supply.",
    ],
    specs: [
      { label: "Product Name", value: "Liquid Sodium Silicate" },
      { label: "Chinese Name", value: "液体硅酸钠" },
      { label: "CAS No.", value: "1344-09-8" },
      { label: "Chemical Formula", value: "Na₂O·nSiO₂" },
      { label: "Forms Available", value: "Liquid and solid (lump/granule)" },
      { label: "Modulus Range", value: "2.0–3.5 (specify on inquiry)" },
      { label: "Appearance (Liquid)", value: "Clear to slightly turbid liquid" },
      { label: "Appearance (Solid)", value: "Colorless to light green lumps/granules" },
      { label: "Solid Content", value: "Confirmed by requested modulus and specification" },
      { label: "Density", value: "Available on request" },
      { label: "pH", value: "Alkaline; confirm by TDS" },
      { label: "Documents Available", value: "TDS, COA, SDS / MSDS on request" },
    ],
    applications: [
      "Detergent and soap manufacturing where liquid silicate is used in formulation",
      "Construction, cement and concrete additive systems",
      "Foundry binder and refractory material applications",
      "Paper, cardboard and pulp processing formulations",
      "Water treatment, soil stabilization and industrial processing uses",
    ],
    packaging: [
      "Liquid: 200 L drums by order requirement",
      "Liquid: 1,000 L IBC tanks for industrial handling review",
      "Liquid: bulk tanker option subject to destination and order volume",
      "Solid form, if required, should be quoted separately as lump, granule or other requested form",
      "Final packing, loading quantity and transport method confirmed before quotation",
    ],
    features: [
      "Liquid sodium silicate focus for buyers comparing modulus and solid content",
      "Modulus, density, appearance and solid content should be confirmed by requested specification",
      "Packing choice depends on handling method, destination, order volume and storage plan",
      "RFQ should include target modulus, solid content, quantity, packing, destination and application",
      "TDS, COA and SDS / MSDS can be requested according to order requirements",
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getMetasilicateGrades(): Product[] {
  return products.filter((p) => p.categoryParent === "sodium-metasilicate");
}

/** @deprecated Use sodiumMetasilicateCategory — category hub is the primary product page */
export function getPrimaryProduct(): Product {
  return products.find((p) => p.slug === "sodium-metasilicate-granules") ?? products[0];
}
